[package]
name = "src-sidecar"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.38"
directories = "6.0.0"
src-lib = { path = "../src-lib" }
jwalk = "0.8.1"
rusqlite = { version = "0.35.0", features = ["bundled"] }
usn-journal-rs = "0.2.1"
runas = "1.2.0"
